manifest:
  name: manifest.json
  dir: './packages/shared/src/configs/'
workflow:
  name: Build CI
  artifact: extension-file
branches-ignore:
  - dependabot/**
comment-threshold: 512
auto-assign:
  - amitsingh-007
