manifest:
  name: manifest.base.json
  dir: './packages/configs/manifest/'
workflow:
  name: Build CI
  artifact: chrome-extension-file
branches-ignore:
  - renovate/**
comment-threshold: 512
auto-assign:
  - amitsingh-007
