language: node_js
node_js:
  - "12"
script:
  - npm ci
  - npm run release

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
