[dev]
  command = "npm run web:dev"
  port = 8888
  targetPort = 3000
  framework = "#custom"

[build]
  base = "web/"
  command = "npm run build"
  publish = "web/out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
