[dev]
  port = 8888
  autoLaunch = false

[build]
  publish = "extension/build"
  functions = "server/routes/"
  targetPort = 5000
  environment = { NODE_VERSION = "14" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"