export const SET_SIGNED_IN_STATUS = "SET_SIGNED_IN_STATUS";

export const SHOW_EDIT_PANEL = "SHOW_EDIT_PANEL";

export const HIDE_EDIT_PANEL = "HIDE_EDIT_PANEL";

export const SHOW_MANUAL_HISTORY_PANEL = "SHOW_MANUAL_HISTORY_PANEL";

export const HIDE_MANUAL_HISTORY_PANEL = "HIDE_MANUAL_HISTORY_PANEL";
