export {
  TEST_BOOKMARKS,
  TEST_FOLDERS,
  TEST_PERSONS,
  TEST_PERSON_NAME,
  TEST_SHORTCUTS,
  TEST_SITES,
  TEST_TIMEOUTS,
  DEFAULT_RULE_ALIAS,
  TEST_CREDENTIALS_KEY,
} from '@bypass/shared/tests';
