export const SET_SIGNED_IN_STATUS = "SET_SIGNED_IN_STATUS";

export const SHOW_EDIT_PANEL = "SHOW_EDIT_PANEL";

export const HIDE_EDIT_PANEL = "HIDE_EDIT_PANEL";

export const SHOW_MANUAL_HISTORY_PANEL = "SHOW_MANUAL_HISTORY_PANEL";

export const HIDE_MANUAL_HISTORY_PANEL = "HIDE_MANUAL_HISTORY_PANEL";

export const TURN_OFF_EXTENSION = "TURN_OFF_EXTENSION";

export const TURN_ON_EXTENSION = "TURN_ON_EXTENSION";

export const START_HISTORY_MONITOR = "START_HISTORY_MONITOR";

export const SHOW_BOOKMARKS_PANEL = "SHOW_BOOKMARKS_PANEL";

export const HIDE_BOOKMARKS_PANEL = "HIDE_BOOKMARKS_PANEL";

export const SHOW_QUICK_BOOKMARK_PANEL = "SHOW_QUICK_BOOKMARK_PANEL";

export const HIDE_QUICK_BOOKMARK_PANEL = "HIDE_QUICK_BOOKMARK_PANEL";
