export const SET_SIGNED_IN_STATUS = "SET_SIGNED_IN_STATUS";

export const TURN_OFF_EXTENSION = "TURN_OFF_EXTENSION";

export const TURN_ON_EXTENSION = "TURN_ON_EXTENSION";

export const START_HISTORY_MONITOR = "START_HISTORY_MONITOR";

export const RESET_HISTORY_MONITOR = "RESET_HISTORY_MONITOR";

export const UPDATE_TAGGED_PERSON_URLS = "UPDATE_TAGGED_PERSON_URLS";

export const SET_AUTHENTICATION_PROGRESS = "SET_AUTHENTICATION_PROGRESS";

export const RESET_AUTHENTICATION_PROGRESS = "SET_AUTHENTICATION_PROGRESS";
